version: 0.0.1
slug: silabs_multiprotocol
name: Silicon Labs Multiprotocol Add-on
description: Zigbee and OpenThread multiprotocol add-on
url: https://github.com/home-assistant/hassio-addons/tree/master/silabs-multiprotocol
arch:
  - armv7
  - aarch64
hassio_api: true
homeassistant: 2021.1.0
privileged:
  - IPC_LOCK
image: homeassistant/{arch}-addon-silabs-multiprotocol
init: false
options:
  device: null
  log_level: info
ports:
  9999/tcp: null
ports_description:
  9999/tcp: EmberZNet EZSP/ASH port
schema:
  device: device(subsystem=tty)
  log_level: list(silly|debug|verbose|http|info|warn|error)?
stage: experimental
startup: services
